---
title: "lyrics_mining"
author: "CMF"
date: "2024-03-15"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

```

```{r}
rm(list = ls())

library(readr)
library(tidyverse)
library(lubridate)
library(tidytext)
library(ggplot2)

```

```{r}
bts_lyrics <- read_csv("lyrics-v12.csv")
bts_lyrics
```

```{r}
bts_lyrics <- bts_lyrics %>% 
  mutate(year = year(album_rd)) %>% 
  select(c(eng_album_title, year, album_seq, eng_track_title, lyrics)) %>%
  na.omit()
  
  

bts_lyrics
```

```{r}
bts_lyrics$lyrics <- iconv(bts_lyrics$lyrics, from = "", to = "UTF-8", sub = " ") # para corregir el error, 

bts_lyrics_rows <- bts_lyrics %>%
  separate_rows(lyrics, sep = "\n") %>%
  group_by(eng_track_title) %>%
  mutate(line_number = row_number()) %>%
  ungroup() %>% 
  mutate(lyrics = gsub("’", "'", lyrics)) # he visto que había un caracter diferente en lyrics y en las stop words que no permitía quitarlas bien, con esto se corrige

bts_lyrics_rows
```

```{r}
# tokenizing
tidy_bts_lyrics <- bts_lyrics_rows %>%
  unnest_tokens(word, lyrics)

tidy_bts_lyrics
```

```{r}
# Filtering stopwords
tidy_bts_lyrics <- tidy_bts_lyrics %>%
  anti_join(stop_words)

tidy_bts_lyrics
```

```{r}
# Counting word frequencies for the whole discography
words <- tidy_bts_lyrics %>%
  count(word, sort = TRUE) 

words
```
```{r}
words %>%
  #only words mentioned over 800 times in the novels
  filter(n > 300) %>%
  #we reorder words by number of mentions
  mutate(word = reorder(word, n)) %>%
  #we create the plot with the word (x) and the number of mentions (y)
  ggplot(aes(n, word)) +
  geom_col() +
  labs(y = NULL)
```

```{r}
# Counting words by album
album_words <- tidy_bts_lyrics %>% 
  count(eng_album_title, word) 

album_words
```


```{r}
# how many total words there are in each album

total_words <- album_words  %>% 
  #we group by books to sum all the totals in the n column of book_words
  group_by(eng_album_title) %>% 
  #we create a column called total with the total of words by book
  summarise(total = sum(n))

total_words
```

```{r}
album_words <- left_join(album_words, total_words, by = "eng_album_title")
album_words
```

```{r}
album_words <- album_words %>%
  #we add a column for term_frequency in each novel
  mutate(term_frequency = n/total)

album_words
```

#### Fifth step: visualize distribution in collection

Let's make a plot to see how words are distributed in the whole Jane Austen's collection

```{r}
#we calculate the distribution and put it in the x axis, filling by book
ggplot(album_words, aes(term_frequency)) +
  #we create the bars histogram
  geom_histogram(show.legend = TRUE) +
  #we set the limit for the term frequency in the x axis
  xlim(NA, 0.0009)
```
